### ISSUE TITLE
TypeError bug for thrift enum use

### ISSUE THREAD

**Issue by aksiazek** [facebookincubator/TestSlide#192]
"TypeError: type of keys of return.failures must be ttypes.EnumType; got int insteadTypeError: type of keys of return.failures must be ttypes.EnumType; got int instead"

These should be equivalent

Full Stacktrace:
$ python3 -m unittest test.TestFrameworkBug

        ERROR: test_repro (test.TestFrameworkBug)
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "/home/alek/.local/lib/python3.6/site-packages/testslide/lib.py", line 184, in _validate_return_type
            _validate_argument_type(expected_type, "return", value)
          File "/home/alek/.local/lib/python3.6/site-packages/testslide/lib.py", line 81, in _validate_argument_type
            typeguard.check_type(name, value, expected_type)
          File "/home/alek/.local/lib/python3.6/site-packages/testslide/lib.py", line 77, in wrapped_check_type
            argname, inner_value, inner_expected_type, *args, **kwargs
          File "/home/alek/.local/lib/python3.6/site-packages/typeguard/__init__.py", line 571, in check_type
            check_tuple(argname, value, expected_type, memo)
          File "/home/alek/.local/lib/python3.6/site-packages/typeguard/__init__.py", line 358, in check_tuple
            check_type('{}.{}'.format(argname, name), getattr(value, name), field_type, memo)
          File "/home/alek/.local/lib/python3.6/site-packages/testslide/lib.py", line 77, in wrapped_check_type
            argname, inner_value, inner_expected_type, *args, **kwargs
          File "/home/alek/.local/lib/python3.6/site-packages/typeguard/__init__.py", line 566, in check_type
            checker_func(argname, value, expected_type, memo)
          File "/home/alek/.local/lib/python3.6/site-packages/typeguard/__init__.py", line 287, in check_dict
            check_type('keys of {}'.format(argname), k, key_type, memo)
          File "/home/alek/.local/lib/python3.6/site-packages/testslide/lib.py", line 77, in wrapped_check_type
            argname, inner_value, inner_expected_type, *args, **kwargs
          File "/home/alek/.local/lib/python3.6/site-packages/typeguard/__init__.py", line 598, in check_type
            format(argname, qualified_name(expected_type), qualified_name(value)))
        a

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "/home/alek/testslide_repro/test.py", line 17, in test_repro
            result = caller.call()
          File "/home/alek/testslide_repro/impl.py", line 15, in call
            return check('arg')
          File "/home/alek/.local/lib/python3.6/site-packages/testslide/lib.py", line 171, in with_sig_and_type_validation
            return value(*args, **kwargs)
          File "/home/alek/.local/lib/python3.6/site-packages/testslide/mock_callable.py", line 512, in __call__
            self._validate_return_type(runner, value)
          File "/home/alek/.local/lib/python3.6/site-packages/testslide/mock_callable.py", line 487, in _validate_return_type
            runner.original_callable, value, self.caller_frame_info
          File "/home/alek/.local/lib/python3.6/site-packages/testslide/lib.py", line 187, in _validate_return_type
            f"{str(type_error)}: {repr(value)}\n"
        TypeError: type of keys of return.failures must be ttypes.EnumType; got int instead: Result(ok=False, failures={0: 'test failure'})
        Defined at /home/alek/.local/lib/python3.6/site-packages/testslide/__init__.py:865

        ----------------------------------------------------------------------
        Ran 1 test in 0.007s

        FAILED (errors=1)
----------------------------------------------------------------------
Code to reproduce bug:

sample.thrift

    enum EnumType{
      NONE               = 0,
    }

ttypes.py (autogenerated via thrift --gen py sample.thrift)

    from thrift.Thrift import TType, TMessageType, TException, TApplicationException

    from thrift.transport import TTransport
    from thrift.protocol import TBinaryProtocol, TProtocol
    try:
      from thrift.protocol import fastbinary
    except:
      fastbinary = None

    class EnumType:
      NONE = 0

      _VALUES_TO_NAMES = {
        0: "NONE",
      }

      _NAMES_TO_VALUES = {
        "NONE": 0,
      }

impl.py

    from ttypes import EnumType
    from typing import Dict, NamedTuple

    class Result(NamedTuple):
        ok: bool
        failures: Dict[EnumType, str]

    def check(param: str) -> Result:
        return Result(ok=False, failures={EnumType.NONE: "test"})

    class Caller:

        def call(self):
            return check('arg')

test.py:

    from testslide import mock_callable
    from testslide import TestCase
    from ttypes import EnumType
    import impl

    class TestFrameworkBug(TestCase):

        def test_repro(self):
            caller = impl.Caller()

            self.mock_callable(impl, "check").to_return_value(
                impl.Result(
                        ok=False,
                        failures={EnumType.NONE: "test failure"},
                    )
                ).and_assert_called_once()
            result = caller.call()
            self.assertEqual(result.ok, False)

**Comment by fornellas** [comment]
@aksiazek thanks for taking the time to report this.

`EnumType` is declared as a regular class, and the type hinting `Dict[EnumType, str]` asks for an instance of it (eg: `EnumType()`). On the `mock_callable` definition, you're passing `EnumType.NONE`, which is defined as `0` (an `int`), which makes the type checking to correctly complain that `0` (`int`) is not an instance of `EnumType`.

The unfortunate name for `EnumType` is deceiving, as it makes us believe this is an `Enum`, but it is just a regular plain class.

The following code works just fine, as it correctly defines the types, and can potentially be how `EnumType` can be fixed:

```python
import testslide, typing

class SomeType(int):
    NONE: typing.ClassVar["SomeType"]

SomeType.NONE = SomeType(0)

class SomeClass:
  def returns_some_type(self) -> SomeType:
    return SomeType.NONE

class ReproTest(testslide.TestCase):
  def test_repro(self):
    some_class_instance = SomeClass()
    self.mock_callable(some_class_instance, "returns_some_type").to_return_value(SomeType.NONE)
    self.assertEqual(some_class_instance.returns_some_type(), SomeType.NONE)
```
